
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Hello sounge developer'
                echo 'Your project change has been built successfully!'
            }
        }
    }
}