
export enum RoleNameEnum {
    GUITARIST, EGUITARIST, VIOLINIST, BASSPLAYER, UKULELEPLAYER,
    DRUMMER, TAMBOURINEPLAYER,
    PIANIST, EKEYBOARDPLAYER, ACCORDIONIST,
    CORNETPLAYER, TROMBONIST, SAXOPHONIST, FLUTIST,
    DJ, PRODUCER, VOCALIST, OTHERS
}