
export enum RoleNameEnum {
    GUITARIST = 'GUITARIST',
    EGUITARIST = 'EGUITARIST',
    VIOLINIST = 'VIOLINIST', 
    BASSPLAYER = 'BASSPLAYER', 
    UKULELEPLAYER = 'UKULELEPLAYER',
    DRUMMER = 'DRUMMER', 
    TAMBOURINEPLAYER = 'TAMBOURINEPLAYER',
    PIANIST = 'PIANIST', 
    EKEYBOARDPLAYER = 'EKEYBOARDPLAYER', 
    ACCORDIONIST = 'ACCORDIONIST',
    CORNETPLAYER = 'CORNETPLAYER', 
    TROMBONIST = 'TROMBONIST', 
    SAXOPHONIST = 'SAXOPHONIST', 
    FLUTIST = 'FLUTIST',
    DJ = 'DJ', 
    PRODUCER = 'PRODUCER', 
    VOCALIST = 'VOCALIST', 
    OTHERS = 'OTHERS'
}

export const RoleNameEnumDesc = new Map<string, string>([
    [RoleNameEnum.GUITARIST, 'Violão'],
    [RoleNameEnum.EGUITARIST, 'Guitarra'],
    [RoleNameEnum.VIOLINIST, 'Violino'],
    [RoleNameEnum.BASSPLAYER, 'Baixo']
])